Refatoracao de address
Hello-Pets/hello-pets-api pull request #17
Opened 2024-06-16 19:08 UTC by Andershowrj

Refatorado porque estava dando erro por possivel nulidade nesta classe

2024-06-16 19:10 UTC, Andershowrj commented
pode ver so o segundo commit porque so tirei as interrogacoes nas propriedades da classe

2024-06-19 22:32 UTC, oGrandeK requested changes

2024-06-19 22:32 UTC, oGrandeK commented on Data/ValueObjects/Address.cs
> +        public static Address Empty => new Address(string.Empty, string.Empty, string.Empty, string.Empty, string.Empty);
Nao entendi isso, tu esta instanciando um ADDRESS com os atributos vazios e nao esta usando isso em lugar nenhum

2024-06-19 22:32 UTC, oGrandeK commented on Data/ValueObjects/Address.cs
> +            if (!string.IsNullOrEmpty(postalCode)) ValidateStringLength(postalCode, 3, 20);
Seu metodo ValidateStringLength esta dentro do V.O de phone number deveriamos tirar o metodo de dentro do V.O para uma classe especifica.

2024-06-19 22:33 UTC, closed without merging