Implementacao de geracao de token
Hello-Pets/hello-pets-api pull request #20
Opened 2024-06-25 21:16 UTC by Andershowrj

A estrutura ja esta toda pronta.
Os middlewares ja estao no projeto.
 Quando iniciar os controllers vai ser setada quais endpoints serao protegidos.

2024-06-27 14:01 UTC, rodgallert commented on Data/JwtBearerConfiguration/PrivateKey.cs
> +    //Esta classe deve ser apagada antes da producao e com uma nova secret key armazenada com seguranca
Remover a classe, utilizar o AppSettings.json para armazenar esse tipo de informacao e futuramente, o KMS da cloud escolhida

2024-06-27 14:01 UTC, rodgallert commented on Data/Services/TokenService.cs
> +            var key = Encoding.ASCII.GetBytes(PrivateKey.Key);
Extrair esse valor do Appsettings.json

se tiver duvida de como fazer, me chama no discord

2024-06-27 14:01 UTC, rodgallert commented on WebApi/Program.cs
> +var key = Encoding.ASCII.GetBytes(PrivateKey.Key);
Remover a referencia da classe e utilizar do appsettings.json

2024-06-27 14:01 UTC, rodgallert commented on WebApi/Program.cs
> +app.UseAuthorization();
Um detalhe e que apenas injetar a autenticacao nao e suficiente pra ela ser necessaria, as rotas e/ou controllers onde a autenticacao e necessaria devem ser anotadas com [Authorize]

2024-06-27 14:01 UTC, rodgallert commented on Data/Services/TokenService.cs
Eu sugeriria uma camada a mais na arquitetura dedicada a services/business, nao faz muito sentido isso estar em data

2024-06-27 14:01 UTC, rodgallert commented on WebApi/Program.cs
> +        ValidateIssuer = false,
Sugiro adicionar tambem o ValidateExpiration, e gerar o JWT com validade curta (ate 7 dias), assim o usuario nao vai ficar eternamente autenticado na plataforma

2024-06-28 01:48 UTC, oGrandeK requested changes

2024-06-28 01:48 UTC, oGrandeK commented on WebApi/Program.cs
> +var key = Encoding.ASCII.GetBytes(PrivateKey.Key);
So estou comentando aqui pra marcar como request changes

2024-06-30 15:08 UTC, Andershowrj commented on WebApi/Program.cs
> +app.UseAuthorization();
isso nas controllers certo?

2024-06-30 15:10 UTC, Andershowrj commented on Data/Services/TokenService.cs
acho que pode ficar pra outra task pra eu conseguir terminar essa se nao nao saio mais daqui kkkk

2024-06-30 15:12 UTC, Andershowrj commented on WebApi/Program.cs
> +        ValidateIssuer = false,
isso nao seria oque esta em tokenservice na linha 33?

2024-06-30 15:15 UTC, Andershowrj commented
em program.cs tem a parte de JWT Configurations que nao tenho certeza se e a melhor forma de fazer... qualquer coisa sugiram novas modificacoes

2024-07-01 14:36 UTC, rodgallert commented on WebApi/Program.cs
> +app.UseAuthorization();
Isso, cada controller ou rota que precisar de autenticacao precisa ser assinada com [Authorize] pra passar pelo middleware, ou [AllowAnonymous] pra abrir uma excecao pra uma rota autenticada

2024-07-01 14:39 UTC, rodgallert commented on WebApi/Program.cs
> +        ValidateIssuer = false,
mais ou menos, la voce adiciona a validade, aqui vai falar pro middleware olhar pra esse campo e dizer se esta valido ou nao
se nao me falha a memoria, isso e default false

2024-07-01 14:58 UTC, rodgallert requested changes

2024-07-01 14:58 UTC, rodgallert commented on Data/Services/TokenService.cs
> +            if (string.IsNullOrEmpty(value)) throw new ArgumentNullException
Existe uma notacao mais limpa, com:
`ArgumentNullException.ThrowIfNull(object, message)`

2024-07-01 14:58 UTC, rodgallert commented on Data/Services/TokenService.cs
Tomei a liberdade de adicionar um [ticket](https://app.clickup.com/t/86a3zv9ab) backlog do Clickup

2024-07-01 14:58 UTC, rodgallert commented on WebApi/appsettings.json
> +    "SecretKey": "W-rAG{CU5ZfFEuGsm5$fzYmM7-f,j>"
Perfeito, futuramente migramos isso pro KMS da Cloud escolhida

2024-07-01 14:58 UTC, rodgallert commented on Data/Services/TokenService.cs
> +                new Claim("nome", tutor.Name),
Name e Email tambem existem no enum JwtRegisteredClaimNames

2024-07-03 20:59 UTC, rodgallert requested changes
faltou so a validacao de lifetime do token

2024-07-03 20:59 UTC, rodgallert commented on WebApi/Program.cs
> +        ValidateIssuer = false,
Adicionar validacao de tempo de vida do token

2024-07-03 21:08 UTC, Andershowrj commented
eu tentei mas nao consegui... como faz?

2024-07-04 19:40 UTC, rodgallert approved these changes

2024-07-04 19:49 UTC, merged