Refatoracoes
Hello-Pets/hello-pets-api pull request #21
Opened 2024-07-01 21:01 UTC by oGrandeK

Fiz algumas refatoraçoes rapidas e simples no codigo e algumas a pedido sua @rodgallert.

Quanto as traduçoes eu ainda nao fiz por que vou precisar estudar com o GPT (kkkk) e ver qual a melhor maneira de traduzir isso, pelo o que andei vendo com o gpt a melhor abordagem seria criar um arquivo externo com a traduçao.

Sobre torna a classe TutorConfiguration estatica nao consegui, se eu marca-se como estatico acusa um erro de que classes estaticas nao podem implementar interfaces.

2024-07-01 22:09 UTC, rodgallert requested changes

2024-07-01 22:09 UTC, rodgallert commented on .vscode/launch.json
> +{
Adicionar essa pasta no .gitignore

2024-07-01 22:09 UTC, rodgallert commented on Data/Entities/Pet.cs
> +    public string TutorId { get; private set; }
Sugiro manter a PK como id, comparacoes entre int podem ser otimizadas e cacheadas de forma mais eficiente que string pelo banco, usando busca binaria.
Se existir a necessidade, criar uma prop PublicId

2024-07-01 22:09 UTC, rodgallert commented on Data/EntitiesConfiguration/PetConfiguration.cs
> +        builder.Property(x => x.Photo).HasColumnName("ProfilePicture").HasMaxLength(255).IsRequired();
Rever esses IsRequired, o documento do pet pode ser vazio, assim como sua foto de perfil e data de nascimento, entre outras coisas

IsRequired vazio sempre define como true

2024-07-01 22:09 UTC, rodgallert commented on Data/EntitiesConfiguration/TutorConfiguration.cs
> +        builder.OwnsOne(x => x.Document).Property(x => x.Type).HasColumnName("DocumentType").IsRequired();
Mesma coisa do PetConfiguration, rever os IsRequired
podemos ver juntos se tiver duvida

2024-07-01 22:09 UTC, rodgallert commented on Data/EntitiesConfiguration/TutorConfiguration.cs
> +        builder.Property(x => x.BirthDate).HasColumnName("BirthDate").IsRequired();
BirthDate ta nullable na classe Tutor, e necessario ou nao?

2024-07-01 22:09 UTC, rodgallert commented on Data/Enums/PersonalitiesEnum.cs
> +    Affectionate = 1,
Da pra remover os numeros, caso nao vai definir outro valor pro campo, e mudar Other pro topo da lista e manter o valor numerico.

Da pra fazer isso salvar no banco como string tambem, alterando a classe de Context

2024-07-01 22:09 UTC, rodgallert commented on Data/Context/ApplicationContext.cs
>          optionsBuilder.UseInMemoryDatabase(databaseName: "BancoDeDadosEmMemoria");
A injecao da dependencia no container ta duplicada, a mesma coisa tambem ta sendo feita na Program

2024-07-01 22:34 UTC, oGrandeK commented on .vscode/launch.json
> +{
irei já, achei que a geraçao do gitignore ja subia isso, nem reparei na hora de subir

2024-07-01 22:39 UTC, oGrandeK commented on Data/Entities/Pet.cs
> +    public string TutorId { get; private set; }
Neste caso eu uso um GUID como ID na base da entidades, um GUID nao seria mais seguro do que botar um ID como int? ou na pratica nao muda nada ou quase nada?

Observar: Value Object de Entity.

2024-07-02 00:11 UTC, rodgallert requested changes

2024-07-02 00:11 UTC, rodgallert commented on .gitignore
> +.vscode
quase, faltou a barra de endereco, tem que ficar .vscode/
se nao vai tratar como extensao de arquivo

2024-07-02 00:11 UTC, rodgallert commented on Data/Entities/Pet.cs
>      public Tutor Tutor { get; private set; } = null!;
esqueci de mencionar isso no review anterior, sempre que for vincular um objeto de relacionamento, adiciona a keyworkd `virtual` na frente do tipo:
`public virtual Tutor`

Mesma coisa pra pets

dessa forma o EF reconhece certo que sao entidades conectadas e nao da problema com tipos nullable

2024-07-03 23:46 UTC, oGrandeK commented on Data/Context/ApplicationContext.cs
>          optionsBuilder.UseInMemoryDatabase(databaseName: "BancoDeDadosEmMemoria");
Nao consegui entender como esta duplicada.

No caso eu deveria remover a linha 14 da program.cs?

@rodgallert

2024-07-04 00:40 UTC, rodgallert requested changes

2024-07-04 00:40 UTC, rodgallert commented on Data/Enums/PersonalitiesEnum.cs
> +    Other = 0,
tirar = 0 desses enums

2024-07-05 01:37 UTC, rodgallert approved these changes

2024-07-05 01:48 UTC, rodgallert approved these changes

2024-07-05 01:50 UTC, merged