Adicionar camada services
Hello-Pets/hello-pets-api pull request #22
Opened 2024-07-07 05:27 UTC by oGrandeK

2024-07-07 05:27 UTC, oGrandeK commented
Essa é pra quem achou que eu nao iria terminar o PR no final de semana

2024-07-07 05:28 UTC, oGrandeK commented on Data/ValueObjects/Password.cs
> +        //Hash = passwordService.CreateHash(password);
Tive que comentar isso para nao dar pau no projeto todo por referencia ciclica entre `Data e Services.`

2024-07-07 20:30 UTC, rodgallert requested changes

2024-07-07 20:30 UTC, rodgallert commented on Services/Application_Services/Interfaces/IPasswordService.cs
> +namespace HelloPets.Services.Application_Services.Interfaces;
Renomear o namespace.

O padrao de nomeacao de namespaces pra .Net e Pascal Case, nao usamos snake case

2024-07-07 20:30 UTC, rodgallert commented on Services/Application_Services/Interfaces/ITokenService.cs
> +namespace Services.Application_Services.Interfaces;
Renomear o namespace.

O padrao de nomeacao de namespaces pra .Net e Pascal Case, nao usamos snake case

2024-07-07 20:30 UTC, rodgallert commented on Data/ValueObjects/Password.cs
> +        //Hash = passwordService.CreateHash(password);
Eventualmente vamos remover essas entidades

2024-07-07 20:30 UTC, rodgallert commented on Services/Application_Services/PasswordService.cs
> +using HelloPets.Services.Application_Services.Interfaces;
Renomear o namespace.

O padrao de nomeacao de namespaces pra .Net e Pascal Case, nao usamos snake case

2024-07-08 06:10 UTC, rodgallert requested changes

2024-07-08 06:10 UTC, rodgallert commented on Services/ApplicationServices/TokenService.cs
>  namespace Services.Application_Services
snake case

2024-07-08 06:10 UTC, rodgallert commented on WebApi/Program.cs
> +builder.Services.AddScoped<ITokenService>();
injetar tambem a implementacao:

`builder.Services.AddScoped<ITokenService, TokenService>();`

2024-07-09 21:55 UTC, rodgallert requested changes

2024-07-09 21:55 UTC, rodgallert commented on Services/ApplicationServices/TokenService.cs
> +            string id = _httpContextAccessor?.HttpContext?.User?.FindFirstValue(ClaimTypes.UserData) ?? "";
Claims sao dicionarios chave/valor, e o nome deve bater

esse aqui dava certo no exemplo que te mandei, mas aqui tem que bater com o id

2024-07-09 23:01 UTC, rodgallert approved these changes

2024-07-09 23:03 UTC, merged