Adicionando base controller
Hello-Pets/hello-pets-api pull request #25
Opened 2024-07-10 20:59 UTC by oGrandeK

2024-07-10 21:06 UTC, rodgallert requested changes
Corrigir tambem os namespaces enviados pelo discord

2024-07-10 21:06 UTC, rodgallert commented on WebApi/Controllers/BaseController.cs
> +[Authorize("")]
authorize deve ser setado individualmente em cada controller/rota, a menos que seja uma configuracao global

2024-07-10 22:09 UTC, rodgallert requested changes

2024-07-10 22:09 UTC, rodgallert commented on WebApi/Controllers/BaseController.cs
> +    private readonly IHttpContextAccessor _httpContextAccessor;
http context accessor nao deve estar aqui

2024-07-10 22:09 UTC, rodgallert commented on WebApi/Controllers/BaseController.cs
> +    private readonly IHttpContextAccessor _httpContextAccessor;
por onde acesso o user id?

2024-07-10 22:19 UTC, oGrandeK commented on WebApi/Controllers/BaseController.cs
> +    private readonly IHttpContextAccessor _httpContextAccessor;
eu sei la qual a classe que acessa o user

2024-07-11 01:01 UTC, rodgallert requested changes

2024-07-11 01:01 UTC, rodgallert commented on WebApi/Controllers/BaseController.cs
> +    private readonly int _userId;
mudar os modificadores de acesso pra serem acessiveis apenas por classes herdeiras

2024-07-11 04:13 UTC, rodgallert requested changes

2024-07-11 04:13 UTC, rodgallert commented on Services/ApplicationServices/Interfaces/ITokenService.cs
>  namespace Services.ApplicationServices.Interfaces;
trocar esse namespace pro padrao

2024-07-11 20:37 UTC, rodgallert approved these changes

2024-07-11 20:38 UTC, oGrandeK commented
Gloria a Deux

2024-07-11 20:38 UTC, merged